### PR TITLE
feat: Create initial repository structure

### PR DESCRIPTION
**Pull request by hwadii**
This is the initial creation of the search api & worker repository.

Used this PR as as a starting point https://github.com/CardioLogs/service-template-dotnet/pull/5.

- [x] initialize project
- [x] add project to sonarcloud
- [ ] add documentation on sonarcloud
- [x] add publish-sf-docs action
- [ ] add ecr repository

### CODE REVIEW

**Comment by spcalvin** [comment]
1. cool
2. we should add an owners file
3. did you make any updates?
4. let's walk through sonarcloud and coveralls ui setup (if needed). i want to document the steps again if they changed

**Comment by hwadii** [comment]
> let's walk through sonarcloud and coveralls ui setup (if needed). i want to document the steps again if they changed

yeah i need to generate a token for this repo and add it to the repo variables. ci fails on the pushing to sonar step

**Comment by spcalvin** [comment]
> > let's walk through sonarcloud and coveralls ui setup (if needed). i want to document the steps again if they changed
> 
> 
> 
> yeah i need to generate a token for this repo and add it to the repo variables. ci fails on the pushing to sonar step

5. ecr updates (terraform maybe)

**Review by spcalvin — APPROVED** [review]
approving so we can test on main

**Pull request merged**
